Repository docker-java/docker-java, pull requests merged in 2020-06, with the labels that each got.

#1371 Support for client certificate chains
  docker-java-core/src/main/java/com/github/dockerjava/core/util/CertificateUtils.java
  docker-java/src/test/java/com/github/dockerjava/core/util/CertificateUtilsTest.java
Labels: type/enhancement

#1405 Add SwarmNodeStatus address field
  docker-java-api/src/main/java/com/github/dockerjava/api/model/SwarmNodeStatus.java
Labels: area/swarm-classic, area/swarm-mode, type/enhancement

#1406 Fix for duplicate key violation for exposed ports
  docker-java-api/src/main/java/com/github/dockerjava/api/model/ExposedPorts.java
  docker-java/src/test/java/com/github/dockerjava/api/model/ExposedPortsTest.java
Labels: type/bug

#1407 do not override pushed image's name
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/PushImageCmdExec.java
  docker-java/src/test/java/com/github/dockerjava/cmd/PushImageCmdIT.java
Labels: type/bug

#1367 Allow filtering by event type
  docker-java-api/src/main/java/com/github/dockerjava/api/command/EventsCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/EventsCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/util/FiltersBuilder.java
  docker-java/src/test/java/com/github/dockerjava/cmd/EventsCmdIT.java
Labels: type/enhancement

#1383 Added support for "--replicas-max-per-node"
  docker-java-api/src/main/java/com/github/dockerjava/api/model/ServicePlacement.java
Labels: area/swarm-classic, area/swarm-mode, type/enhancement

#1262 Add resize container and exec command
  docker-java-api/src/main/java/com/github/dockerjava/api/DockerClient.java
  docker-java-api/src/main/java/com/github/dockerjava/api/command/DelegatingDockerCmdExecFactory.java
  docker-java-api/src/main/java/com/github/dockerjava/api/command/DockerCmdExecFactory.java
  docker-java-api/src/main/java/com/github/dockerjava/api/command/ResizeContainerCmd.java
  docker-java-api/src/main/java/com/github/dockerjava/api/command/ResizeExecCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/AbstractDockerCmdExecFactory.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/ResizeContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/ResizeExecCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/ResizeContainerCmdExec.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/ResizeExecCmdExec.java
  docker-java/src/test/java/com/github/dockerjava/cmd/ResizeContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/ResizeExecCmdIT.java
Labels: type/feature

#1414 Always catch exceptions from `close()`
  docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/JerseyDockerHttpClient.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
Labels: transport/jersey, transport/okhttp, type/bug

#1415 auto close in `ResultCallback#awaitCompletion`
  docker-java-api/src/main/java/com/github/dockerjava/api/async/ResultCallbackTemplate.java
Labels: type/enhancement

#1416 docs: fix typo in transports.md
  docs/transports.md
Labels: type/docs

#1418 Catch more generic `FileSystemException` in `NamedPipeSocket`
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/NamedPipeSocket.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/NamedPipeSocket.java
Labels: os/win, type/bug

#1420 Catch `AssertionError` when closing OkHttp's response
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
Labels: transport/okhttp, type/bug

#1421 Detect leaked `DockerHttpClient.Response` objects
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultInvocationBuilder.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/ResizeContainerCmdExec.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/ResizeExecCmdExec.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/DockerHttpClientLeakDetector.java
  docker-java/src/test/java/com/github/dockerjava/cmd/SaveImageCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/SaveImagesCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/TrackingDockerHttpClient.java
Labels: transport/httpclient5, transport/jersey, transport/okhttp, type/bug

#1422 Update "checkout" action to v2
  .github/workflows/ci.yml
Labels: type/housekeeping

#1412 Memoize file match patterns
  docker-java-core/src/main/java/com/github/dockerjava/core/GoLangFileMatch.java
Labels: type/enhancement
