Repository docker-java/docker-java, pull requests merged in 2020-05, with the labels that each got.

#1374 Add lombok annotations for LogConfig (#1373)
  docker-java-api/src/main/java/com/github/dockerjava/api/model/LogConfig.java
  docker-java/src/test/java/com/github/dockerjava/api/model/HostConfigTest.java
Labels: type/enhancement

#1396 Port Travis to GHA
  .ci/get-docker-com.sh
  .ci/setup_docker.sh
  .editorconfig
  .github/workflows/ci.yml
  .travis.yml
  .travis/travis-before-install.sh
  docker-java-api/src/main/java/com/github/dockerjava/api/command/PullImageResultCallback.java
  docker-java-api/src/main/java/com/github/dockerjava/api/exception/DockerException.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java
  docker-java/pom.xml
  docker-java/src/test/java/com/github/dockerjava/cmd/PushImageCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateSecretCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateServiceCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/InitializeSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/JoinSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/LeaveSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListSecretCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListServicesCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListTasksCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/LogSwarmObjectIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/MultiNodeSwarmCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/SwarmCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/UpdateSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/UpdateSwarmNodeIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/UpdateSwarmServiceIT.java
  docker-java/src/test/java/com/github/dockerjava/core/DefaultDockerClientConfigTest.java
  docker-java/src/test/java/com/github/dockerjava/test/serdes/JSONTestHelper.java
Labels: type/housekeeping

#1345 Add missing fields to Image
  docker-java-api/src/main/java/com/github/dockerjava/api/model/Image.java
Labels: impact/minor, type/enhancement

#1366 Add other event types
  docker-java-api/src/main/java/com/github/dockerjava/api/model/EventType.java
Labels: type/enhancement

#1397 Fix Netty leaks
  docker-java-transport-netty/src/main/java/com/github/dockerjava/netty/NettyInvocationBuilder.java
Labels: transport/netty, type/bug

#1398 Do not use fixed names/ports in `MultiNodeSwarmCmdIT`
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/MultiNodeSwarmCmdIT.java
Labels: area/swarm-mode, type/housekeeping

#1399 Alwlays use DinD in Swarm tests
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateSecretCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateServiceCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/InitializeSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/JoinSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/LeaveSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListSecretCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListServicesCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListTasksCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/LogSwarmObjectIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/MultiNodeSwarmCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/SwarmCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/UpdateSwarmCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/UpdateSwarmNodeIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/UpdateSwarmServiceIT.java
Labels: type/housekeeping

#1385 Fix ListSwarmNodesCmdImpl and Add basic tests
  docker-java-core/src/main/java/com/github/dockerjava/core/command/ListSwarmNodesCmdImpl.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListSwarmNodesCmdExecIT.java
Labels: area/swarm-mode

#1401 Explain deprecations
  docker-java-api/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/AttachContainerResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/BuildImageResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/EventsResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/ExecStartResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/LogContainerResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/PullImageResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/PushImageResultCallback.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/WaitContainerResultCallback.java
Labels: type/docs

#1387 Fix HostConfig's NanoCpus JsonProperty wrong casing
  docker-java-api/src/main/java/com/github/dockerjava/api/model/HostConfig.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CreateContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/InspectContainerCmdIT.java
Labels: type/bug

#1402 Introduce `docker-java-transport` module
  docker-java-core/pom.xml
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerCmdExecFactory.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultInvocationBuilder.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/FramedInputStreamConsumer.java
  docker-java-core/src/main/java/com/github/dockerjava/core/SSLConfig.java
  docker-java-transport-httpclient5/pom.xml
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClient.java
  docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/JerseyDockerCmdExecFactory.java
  docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/JerseyDockerHttpClient.java
  docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/filter/ResponseStatusExceptionFilter.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/HijackingInterceptor.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkHttpDockerCmdExecFactory.java
  docker-java-transport/pom.xml
  docker-java-transport/src/main/java/com/github/dockerjava/transport/DockerHttpClient.java
  docker-java-transport/src/main/java/com/github/dockerjava/transport/SSLConfig.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CmdIT.java
  docker-java/src/test/java/com/github/dockerjava/core/command/DockerfileFixture.java
  pom.xml
Labels: type/enhancement

#1403 Rework DockerHttpClient API
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientImpl.java
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClient.java
  docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/JerseyDockerCmdExecFactory.java
  docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/JerseyDockerHttpClient.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkHttpDockerCmdExecFactory.java
  docker-java/pom.xml
  docker-java/src/main/java/com/github/dockerjava/core/DockerClientBuilder.java
  docker-java/src/test/java/com/github/dockerjava/cmd/AttachContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CommitCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/ConnectToNetworkCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/ContainerDiffCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CopyArchiveFromContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CreateContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CustomCommandIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/ExecCreateCmdImplIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/InfoCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/UpdateContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateServiceCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListServicesCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListTasksCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/SwarmCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerClientDelegate.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerCmdExecFactoryDelegate.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerRule.java
  docker-java/src/test/java/com/github/dockerjava/core/TestDockerCmdExecFactory.java
  docker-java/src/test/java/com/github/dockerjava/junit/DockerAssume.java
  docker-java/src/test/java/com/github/dockerjava/junit/DockerMatchers.java
  docker-java/src/test/java/com/github/dockerjava/junit/PrivateRegistryRule.java
Labels: type/enhancement
