Repository docker-java/docker-java, pull requests merged in 2021-12, with the labels that each got.

#1746 Update apache commons-lang (2) to current commons-lang3
  docker-java-core/pom.xml
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerCmdExecFactory.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerConfigFile.java
  docker-java-core/src/main/java/com/github/dockerjava/core/GoLangFileMatch.java
  docker-java-core/src/main/java/com/github/dockerjava/core/NameParser.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/AbstrDockerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/CopyArchiveToContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/CreateContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/InitializeSwarmCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/JoinSwarmCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/ListImagesCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/LogContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/UpdateContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/UpdateServiceCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/UpdateSwarmNodeCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/dockerfile/DockerfileStatement.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/BuildImageCmdExec.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/TopContainerCmdExec.java
  docker-java-transport-netty/src/main/java/com/github/dockerjava/netty/NettyDockerCmdExecFactory.java
  docker-java-transport-netty/src/main/java/com/github/dockerjava/netty/NettyWebTarget.java
  docker-java/src/test/java/com/github/dockerjava/api/ModelsSerializableTest.java
  docker-java/src/test/java/com/github/dockerjava/cmd/TagImageCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/VersionCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateConfigCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/CreateSecretCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/InspectConfigCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListConfigCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/ListSecretCmdExecIT.java
  docker-java/src/test/java/com/github/dockerjava/core/DefaultDockerClientConfigTest.java
  docker-java/src/test/java/com/github/dockerjava/core/NameParserTest.java
  docker-java/src/test/java/com/github/dockerjava/core/RemoteApiVersionTest.java
  docker-java/src/test/java/com/github/dockerjava/utils/TestUtils.java
  docker-java/template.mf
  pom.xml
Labels: dependencies

#1735 add missing cmd `RemoveSwarmNodeCmd` in client
  docker-java-api/src/main/java/com/github/dockerjava/api/DockerClient.java
  docker-java-api/src/main/java/com/github/dockerjava/api/DockerClientDelegate.java
  docker-java-api/src/main/java/com/github/dockerjava/api/command/RemoveSwarmNodeCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/RemoveSwarmNodeCmdImpl.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/RemoveSwarmNodeCmdExecIT.java
Labels: type/enhancement, area/swarm-mode

#1734 add `until` param with LogContainerCmd
  docker-java-api/src/main/java/com/github/dockerjava/api/command/LogContainerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/LogContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/LogContainerCmdExec.java
  docker-java/src/test/java/com/github/dockerjava/cmd/LogContainerCmdIT.java
Labels: type/enhancement

#1713 Fix wrong field returned in getter
  docker-java-api/src/main/java/com/github/dockerjava/api/model/ContainerMount.java
Labels: type/bug, resolution/acknowledged
