Repository docker-java/docker-java, pull requests merged in 2021-06, with the labels that each got.

#1638 Add `platform` to `CreateContainerCmd`
  docker-java-api/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/CreateContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/CreateContainerCmdExec.java
Labels: type/enhancement

#1617 Allow overriding timeouts of Apache HttpClient5 transport
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClient.java
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClientImpl.java
  docker-java-transport-zerodep/src/main/java/com/github/dockerjava/httpclient5/ZerodepDockerHttpClient.java
  docs/getting_started.md
Labels: transport/httpclient5

#1652 Ensure the compatibility with old (2.8.8) Jackson versions
  docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientConfig.java
  docker-java/pom.xml
Labels: dependencies, type/bug
