Repository docker-java/docker-java, pull requests merged in 2021-09, with the labels that each got.

#1627 Add java16 unix socket support
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClientImpl.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/UnixSocketFactory.java
  docker-java-transport/src/main/java/com/github/dockerjava/transport/DomainSocket.java
  docker-java-transport/src/main/java/com/github/dockerjava/transport/UnixSocket.java
Labels: resolution/acknowledged

#1702 Disable socket timeout of 3min introduced in #1590
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClientImpl.java
Labels: type/bug, transport/httpclient5

#1701 Use npipe as the default DOCKER_HOST on Windows
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java
Labels: type/enhancement

#1707 Add `DockerClientDelegate`
  docker-java-api/src/main/java/com/github/dockerjava/api/DockerClientDelegate.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CustomCommandIT.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerClientDelegate.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerRule.java
Labels: type/enhancement
