Repository docker-java/docker-java, pull requests merged in 2022-02, with the labels that each got.

#1769 Use a non-blocking output stream for socket writes
  docker-java-transport/src/main/java/com/github/dockerjava/transport/UnixSocket.java
Labels: type/bug, os/mac, os/linux

#1801 Support path of DOCKER_HOST
  docker-java-transport-httpclient5/pom.xml
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClientImpl.java
  docker-java-transport-httpclient5/src/test/java/com/github/dockerjava/transport/HttpClient5Tests.java
  docker-java-transport-jersey/pom.xml
  docker-java-transport-jersey/src/test/java/com/github/dockerjava/transport/JerseyTests.java
  docker-java-transport-okhttp/pom.xml
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
  docker-java-transport-okhttp/src/test/java/com/github/dockerjava/transport/OkHttpClientTests.java
  docker-java-transport-tck/pom.xml
  docker-java-transport-tck/src/main/java/com/github/dockerjava/transport/DockerHttpClientTCK.java
  pom.xml
Labels: transport/jersey, type/feature, transport/okhttp, transport/httpclient5

#1803 Do not parameterize command tests, use TCK
  .ci/setup_docker.sh
  .github/workflows/ci.yml
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java
  docker-java-transport-jersey/src/test/java/com/github/dockerjava/transport/JerseyTests.java
  docker-java-transport-tck/pom.xml
  docker-java-transport-tck/src/main/java/com/github/dockerjava/transport/DockerHttpClientTCK.java
  docker-java/src/test/java/com/github/dockerjava/cmd/AttachContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/ConnectToNetworkCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CopyArchiveFromContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CopyArchiveToContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CopyFileFromContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CreateContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CreateNetworkCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CustomCommandIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/DisconnectFromNetworkCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/PushImageCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/RemoveVolumeCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/RenameContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/StartContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/swarm/SwarmCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerRule.java
  docker-java/src/test/java/com/github/dockerjava/junit/PrivateRegistryRule.java
Labels: type/housekeeping

#1788 Add npipe as a valid mount type
  docker-java-api/src/main/java/com/github/dockerjava/api/model/MountType.java
Labels: type/enhancement, dependencies

#1805 Use POSIX for tar long file mode and big number mode.
  docker-java-core/src/main/java/com/github/dockerjava/core/util/CompressArchiveUtil.java
Labels: type/enhancement

#1807 Do not leak `AuthConfig` into `CreateContainerCmd`'s JSON
  docker-java-core/src/main/java/com/github/dockerjava/core/command/CreateContainerCmdImpl.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CreateContainerCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/core/DockerRule.java
Labels: type/bug

#1816 Remove `jna-transport` dependency from `okhttp`
  docker-java-transport-okhttp/pom.xml
Labels: type/housekeeping, transport/okhttp

#1817 Rename `RestartContainerCmd#withtTimeout` to `#withTimeout`
  docker-java-api/src/main/java/com/github/dockerjava/api/command/RestartContainerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/RestartContainerCmdImpl.java
Labels: type/bug

#1818 Relax protocol check in `DefaultDockerClientConfig`
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClientImpl.java
  docker-java-transport-okhttp/src/main/java/com/github/dockerjava/okhttp/OkDockerHttpClient.java
  docker-java/src/test/java/com/github/dockerjava/core/DefaultDockerClientConfigTest.java
Labels: type/enhancement
