Repository docker-java/docker-java, pull requests merged in 2023-10, with the labels that each got.

#2188 Fixing flaky test `ListContainersCmdIT.testStatusFilter`
  docker-java/src/test/java/com/github/dockerjava/cmd/ListContainersCmdIT.java
Labels: type/housekeeping

#2187 Add units (nanoseconds) to HealthCheck.
  docker-java-api/src/main/java/com/github/dockerjava/api/model/HealthCheck.java
Labels: type/docs

#2189 Improve assertions
  docker-java/src/test/java/com/github/dockerjava/cmd/ListContainersCmdIT.java
Labels: type/housekeeping

#2186 Add signal query argument for Restart Container command
  docker-java-api/src/main/java/com/github/dockerjava/api/command/RestartContainerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/RemoteApiVersion.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/RestartContainerCmdImpl.java
  docker-java-core/src/main/java/com/github/dockerjava/core/exec/RestartContainerCmdExec.java
  docker-java/src/test/java/com/github/dockerjava/cmd/RestartContainerCmdImplIT.java
Labels: type/enhancement
