Repository docker-java/docker-java, pull requests merged in 2024-07, with the labels that each got.

#2346 Update images
  docker-java/src/test/java/com/github/dockerjava/cmd/ListContainersCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/PullImageCmdIT.java
Labels: type/housekeeping

#2335 Consider already existing images as successful pulls.
  docker-java-api/src/main/java/com/github/dockerjava/api/model/PullResponseItem.java
  docker-java/src/test/java/com/github/dockerjava/api/model/PullResponseItemTest.java
  docker-java/src/test/java/com/github/dockerjava/api/model/PullResponseJSONSamples.java
  docker-java/src/test/resources/com/github/dockerjava/api/model/pullImageResponse_alreadyExists.json
Labels: type/bug

#2344 Add Network create attribute
  docker-java-api/src/main/java/com/github/dockerjava/api/model/Network.java
  docker-java/src/test/java/com/github/dockerjava/cmd/CreateNetworkCmdIT.java
  docker-java/src/test/java/com/github/dockerjava/cmd/InspectNetworkCmdIT.java
Labels: type/enhancement

#2337 Enable protocol configuration of SSLContext
  docker-java-core/src/main/java/com/github/dockerjava/core/LocalDirectorySSLConfig.java
Labels: type/enhancement
