Repository docker-java/docker-java, pull requests merged in 2024-02, with the labels that each got.

#2279 Enable japicmp in docker-java-api module
  docker-java-api/pom.xml
  docker-java-api/src/main/java/com/github/dockerjava/api/command/InspectContainerResponse.java
  docker-java/src/test/java/com/github/dockerjava/cmd/InspectContainerCmdIT.java
  pom.xml
Labels: type/housekeeping

#2244 Add StartInterval to health check since it will be supported by the 1.44 docker API
  .gitignore
  docker-java-api/src/main/java/com/github/dockerjava/api/model/HealthCheck.java
  docker-java-core/src/main/java/com/github/dockerjava/core/RemoteApiVersion.java
  docker-java/src/test/java/com/github/dockerjava/cmd/HealthCmdIT.java
Labels: type/enhancement

#2292 Add missing states in ServiceUpdateState
  docker-java-api/src/main/java/com/github/dockerjava/api/model/ServiceUpdateState.java
Labels: type/enhancement

#2305 If BuildImage fails but logs something about success, don't succeed
  docker-java-api/src/main/java/com/github/dockerjava/api/command/BuildImageResultCallback.java
Labels: type/bug

#2311 Add `Runtimes` to `Info` response
  docker-java-api/src/main/java/com/github/dockerjava/api/model/Info.java
  docker-java-api/src/main/java/com/github/dockerjava/api/model/RuntimeInfo.java
  docker-java/src/test/java/com/github/dockerjava/cmd/InfoCmdIT.java
Labels: type/enhancement
