Repository docker-java/docker-java, pull requests merged in 2025-04, with the labels that each got.

#2364 Upgrade Apache HttpClient to version 5.4
  docker-java-transport-httpclient5/pom.xml
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/ApacheDockerHttpClientImpl.java
  docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/HijackingHttpRequestExecutor.java
Labels: dependencies

#2392 Fix InspectContainerResponse data types to be able to hold an int64
  docker-java-api/pom.xml
  docker-java-api/src/main/java/com/github/dockerjava/api/command/InspectContainerResponse.java
  docker-java/src/test/java/com/github/dockerjava/cmd/InspectContainerCmdIT.java
Labels: type/breaking-change

#2389 Add some missed options to UpdateContainerCmd
  docker-java-api/pom.xml
  docker-java-api/src/main/java/com/github/dockerjava/api/command/UpdateContainerCmd.java
  docker-java-core/src/main/java/com/github/dockerjava/core/command/UpdateContainerCmdImpl.java
  docker-java/src/test/java/com/github/dockerjava/api/command/CommandJSONSamples.java
  docker-java/src/test/java/com/github/dockerjava/api/command/UpdateContainerResponseTest.java
  docker-java/src/test/java/com/github/dockerjava/cmd/UpdateContainerCmdIT.java
  docker-java/src/test/resources/com/github/dockerjava/api/command/updateContainerResponse_empty.json
  docker-java/src/test/resources/com/github/dockerjava/api/command/updateContainerResponse_warnings.json
Labels: type/housekeeping, type/breaking-change

#2416 Fix possible CME while replacing properties
  docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java
Labels: type/bug

#2300 Bump com.google.guava:guava from 19.0 to 33.4.6-jre
  pom.xml
Labels: dependencies
